import type { Metadata } from "next";
import IsAuth from "../Auth/IsAuth/IsAuth";

export const metadata: Metadata = {
  title: {
    default: `Dashb`,
    template: `%s - Dashbs`
  },
  description: "Generated by create next app",
};

export default async function Layout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  let isAuth = await IsAuth()

  return (
    <>
     {isAuth ? children : auth}
    </>
  );
}
