import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies, headers } from "next/headers";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let h = await headers()
  let c = await cookies()
  // 
  let theme: any = `system`
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${theme} antialiased`}
      >
        <Toaster closeButton duration={20000} richColors position={`bottom-center`} theme={theme}/>
        {children}
      </body>
    </html>
  );
}
