import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: `Authentication`,
    template: `%s - Authentications`
  },
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
     {children}
    </>
  );
}
