import type { Metadata } from "next";
import { AnimatedBackground } from "./Components/animated-background";
import SetToken, { getClientIP } from "@/app/Auth/IsAuth/SetToken";
import Script from "next/script";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: {
    default: `Authentication`,
    template: `%s - Authentications`
  },
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let h = await headers()
  let au = h.get(`user-agent`)?.split(/\s+/).join('')
  let token = await SetToken()
  // 
  let ky = [`${au}`, `${await getClientIP(h)}`]
  let session = await SetToken({
    expiresIn: '10m',
    algorithm: 'HS512'
  }, ky)
  // 
  return (
    <>
    <Script defer>
      {`if (typeof window !== 'undefined') {
        window.document.cookie = '_athk_=${token}';
      }`}
    </Script>
    {/*  */}
    <AnimatedBackground/>
     {children}
    </>
  );
}
