version: '3.8'

services:
  recommendation-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G